/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main.java.view;

import java.awt.Color;
import java.awt.Cursor;

import javax.swing.JOptionPane;

import main.java.data.Pessoa;
import main.java.service.ForumPostService;
import main.java.service.ForumService;

import main.java.service.NotaService;
import main.java.service.PessoaService;
import main.java.service.ServiceException;

import main.java.view.CustomComponents.GradientButton;
import main.java.view.CustomComponents.GradientPanel;

/**
 *
 * @author Vit0ncio
 */
public class TelaNotas extends javax.swing.JFrame {
    private final Pessoa usuario;
    private final NotaService notaService;
    private final ForumService forumService;
    private final PessoaService pessoaService;
    private final ForumPostService forumPostService;

    /**
     * Creates new form TelaNotas
     * @param usuario
     * @param notaService
     * @param pessoaService
     * @param forumService
     * @param forumPostService
     */
    public TelaNotas(Pessoa usuario, PessoaService pessoaService, ForumService forumService, ForumPostService forumPostService, NotaService notaService
    ) {
        this.usuario = usuario;
        this.notaService = notaService;
        this.pessoaService = pessoaService;
        this.forumService = forumService;
        this.forumPostService = forumPostService;
    
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Notas");
        
        carregarNotas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabNotas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btSair = new GradientButton(new Color(207, 0, 0), new Color(255, 0, 0));
        jPanel2 =  new GradientPanel(new Color(1, 239, 110), new Color(0, 132, 246));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setName(""); // NOI18N

        tabNotas.setEnabled(false);
        tabNotas.setBackground(new java.awt.Color(255, 255, 255));
        tabNotas.setForeground(new java.awt.Color(0, 0, 0));
        tabNotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Semestre 1: 6", "Semestre 2: 1", "Semestre 1: 6", "Semestre 2: 1"},
                {"Semestre 1: 6", "Semestre 2: 1", "Semestre 1: 6", "Semestre 2: 1"},
            },
            new String [] {
                "Matéria 1", "Matéria 2", "Matéria 3", "Matéria 4"
            }
        ));
        jScrollPane1.setViewportView(tabNotas);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setText("Notas");

        btSair.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        btSair.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 88, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(152, 152, 152)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        // TODO add your handling code here:
        try {
            TelaPrincipal principal = new TelaPrincipal(usuario, pessoaService, forumService, forumPostService, notaService);
            principal.setVisible(true);
            dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao ir para a tela principal: " + e.getMessage());
        }
    }//GEN-LAST:event_btSairActionPerformed
    private void carregarNotas() {
        try {
            var notas = notaService.listarNotasDoAluno(usuario.getId());

            String[] colunas = { "Matéria", "Semestre", "Nota" };
            Object[][] dados = new Object[notas.size()][3];

            for (int i = 0; i < notas.size(); i++) {
                dados[i][0] = notas.get(i).getMateria();
                dados[i][1] = notas.get(i).getSemestre();
                dados[i][2] = notas.get(i).getValor();
            }

            tabNotas.setModel(new javax.swing.table.DefaultTableModel(dados, colunas));
        } catch (ServiceException se) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar notas: " + se.getMessage());
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabNotas;
    // End of variables declaration//GEN-END:variables
}
