package view;

import data.Forum;
import data.ForumPost;
import data.Pessoa;

import dao.ForumDAO;
import dao.ForumPostDAO;
import dao.PessoaDAO;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

import java.util.ArrayList;

import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

import view.CustomComponents.GradientButton;
import view.CustomComponents.GradientPanel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Vit0ncio
 */
public class TelaForum extends javax.swing.JFrame {
    private ArrayList<Forum> forums;
    private JPanel pnlPosts;
    /**
     * Creates new form TelaForum
     */
    public TelaForum() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Forum");
        
        pnlPosts = new JPanel();
        pnlPosts.setLayout(new javax.swing.BoxLayout(pnlPosts, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(pnlPosts);

        forums = (ArrayList<Forum>) new ForumDAO().listarTodosForuns();
        if (forums.isEmpty()) {
            criarPosts();
        }
        
        exibirPosts();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btSair = new GradientButton(new Color(207, 0, 0), new Color(255, 0, 0));
        jScrollPane1 = new javax.swing.JScrollPane();
        listaTopicos = new javax.swing.JList<>();
        jPanel2 = new GradientPanel(new Color(1, 239, 110), new Color(0, 132, 246));

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel2.setText("Fórum");

        btSair.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        btSair.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        listaTopicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaTopicosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listaTopicos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 88, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(151, 151, 151)
                        .addComponent(jLabel2)
                        .addGap(0, 254, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        // TODO add your handling code here:
        try {
            TelaPrincipal principal = new TelaPrincipal();
            principal.setVisible(true);
            dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao ir para a tela principal: " + e.getMessage());
        }
    }//GEN-LAST:event_btSairActionPerformed

    private void listaTopicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaTopicosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_listaTopicosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaForum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaForum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaForum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaForum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaForum().setVisible(true);
            }
        });
    }
    
    private void criarPosts() {
        if (forums.isEmpty()) {
            ForumDAO forumDAO = new ForumDAO();

            Forum forumInicio = new Forum("Início");
            forumDAO.adicionarForum(forumInicio);
            forums.add(forumInicio);
 
            Forum forumDuvidas = new Forum("Dúvidas");
            forumDAO.adicionarForum(forumDuvidas);
            forums.add(forumDuvidas);
 
            ForumPostDAO postDAO = new ForumPostDAO();
            PessoaDAO pessoaDAO = new PessoaDAO();

            Pessoa instituicao = pessoaDAO.buscarPorEmail("instituicao@educonnect.com");
            if (instituicao == null) {
                instituicao = new Pessoa(1, "Instituição", 0, "instituicao@educonnect.com", "instituicao");
                pessoaDAO.salvar(instituicao, "instituicao");
            }
        
            ForumPost postBoasVindas = new ForumPost();
            postBoasVindas.setTitulo("Boas-Vindas!");
            postBoasVindas.setDescricao("Seja bem-vindo ao fórum EduConnect!");
            postBoasVindas.setAutor(instituicao);
            postBoasVindas.setFixado(true);
            postBoasVindas.setUpvotes(89);
            postBoasVindas.setForum(forumInicio);
            postDAO.adicionarPost(postBoasVindas);
        
            Pessoa professor = pessoaDAO.buscarPorEmail("professor@educonnect.com");
            if (professor == null) {
                professor = new Pessoa(2, "Professor", 0, "professor@educonnect.com", "professor");
                pessoaDAO.salvar(professor, "professor");
            }

            ForumPost postTopicoPrincipal = new ForumPost();
            postTopicoPrincipal.setTitulo("Tópico Principal");
            postTopicoPrincipal.setDescricao("Discussões gerais sobre o curso");
            postTopicoPrincipal.setAutor(professor);
            postTopicoPrincipal.setFixado(true);
            postTopicoPrincipal.setUpvotes(45);
            postTopicoPrincipal.setForum(forumDuvidas);
            postDAO.adicionarPost(postTopicoPrincipal);

            Pessoa aluno = pessoaDAO.buscarPorEmail("aluno@educonnect.com");
            if (aluno == null) {
                aluno = new Pessoa(3, "Aluno", 0, "aluno@educonnect.com", "aluno");
                pessoaDAO.salvar(aluno, "aluno");
            }

            ForumPost postDuvidasAtv1 = new ForumPost();
            postDuvidasAtv1.setTitulo("Dúvidas atv1");
            postDuvidasAtv1.setDescricao("Alguém pode ajudar com a atividade 1?");
            postDuvidasAtv1.setAutor(aluno);
            postDuvidasAtv1.setUpvotes(-2);
            postDuvidasAtv1.setForum(forumDuvidas);
            postDAO.adicionarPost(postDuvidasAtv1);
    }
}
    
    private void exibirPosts() {
        pnlPosts.removeAll();
        
        for (Forum forum : forums) {
            JLabel lblTituloForum = new JLabel(forum.getTopico());
            lblTituloForum.setFont(new Font("Arial", Font.BOLD, 18));
            lblTituloForum.setBorder(BorderFactory.createEmptyBorder(10, 5, 5, 5));
            pnlPosts.add(lblTituloForum);
            
            for (ForumPost post : forum.getPosts()) {
                pnlPosts.add(criarPostEmLinha(post));
            }
        }
        
        pnlPosts.revalidate();
        pnlPosts.repaint();
    }

    private JPanel criarPostEmLinha(ForumPost post) {
        JPanel panel = new JPanel();
        panel.setLayout(new BorderLayout());
        panel.setBorder(BorderFactory.createCompoundBorder(
            BorderFactory.createLineBorder(Color.LIGHT_GRAY, 1),
            BorderFactory.createEmptyBorder(5, 10, 5, 10)
        ));
        
        final int TAMANHO_ICONE = 24;

        JPanel pnlConteudo = new JPanel(new BorderLayout());

        if (post.isFixado()) {
            JLabel lblAncora = new JLabel(redimensionarIcone("/logos/fixo.png", TAMANHO_ICONE, TAMANHO_ICONE));
            lblAncora.setToolTipText("Post fixado");
            pnlConteudo.add(lblAncora, BorderLayout.WEST);
        }

        JLabel lblPost = new JLabel("<html><b>" + post.getTitulo() + "</b> - " + post.getDescricao() + "</html>");
        lblPost.setFont(new Font("Arial", Font.PLAIN, 12));
        pnlConteudo.add(lblPost, BorderLayout.CENTER);

        JPanel pnlAcoes = new JPanel();
        
        JLabel lblFavorito = new JLabel(redimensionarIcone(post.isFavoritado() ? "/logos/coracao_preenchido.png" : "/logos/coracao.png", TAMANHO_ICONE, TAMANHO_ICONE));
        lblFavorito.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        lblFavorito.setToolTipText(post.isFavoritado() ? "Remover dos favoritos" : "Adicionar aos favoritos");
        lblFavorito.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                toggleFavorito(post);
            }
        });
        
        JLabel lblVotos = new JLabel(String.valueOf(post.getUpvotes()));
        lblVotos.setFont(new Font("Arial", Font.BOLD, 12));
        lblVotos.setForeground(post.getUpvotes() >= 0 ? Color.GREEN : Color.RED);

        JLabel lblUpvote = new JLabel(redimensionarIcone("/logos/like.png", TAMANHO_ICONE, TAMANHO_ICONE));
        lblUpvote.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        lblUpvote.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                votarPost(post, 1);
            }
        });

        JLabel lblDownvote = new JLabel(redimensionarIcone("/logos/dislike.png", TAMANHO_ICONE, TAMANHO_ICONE));
        lblDownvote.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        lblDownvote.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                votarPost(post, -1);
            }
        });
        
        pnlAcoes.add(lblFavorito);
        pnlAcoes.add(lblUpvote);
        pnlAcoes.add(lblVotos);
        pnlAcoes.add(lblDownvote);
        
        pnlConteudo.add(pnlAcoes, BorderLayout.EAST);
        panel.add(pnlConteudo, BorderLayout.CENTER);
        
        return panel;
    }
    
    private ImageIcon redimensionarIcone(String caminho, int largura, int altura) {
        ImageIcon iconOriginal = new ImageIcon(getClass().getResource(caminho));
        Image imgRedimensionada = iconOriginal.getImage().getScaledInstance(largura, altura, Image.SCALE_SMOOTH);
        return new ImageIcon(imgRedimensionada);
    }
    
    private void toggleFavorito(ForumPost post) {
        post.setFavoritado(!post.isFavoritado());
        exibirPosts();
    }
    
    private void votarPost(ForumPost post, int voto) {
        post.setUpvotes(post.getUpvotes() + voto);
        exibirPosts();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSair;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listaTopicos;
    // End of variables declaration//GEN-END:variables
}
