/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;
import java.awt.Cursor;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

import view.CustomComponents.GradientButton;
import view.CustomComponents.GradientPanel;


/**
 *
 * @author Vit0ncio
 */
public class TelaTarefas extends javax.swing.JFrame {
    private String comentarioSalvo = "";
    private String arquivoSalvo = "";
    /**
     * Creates new form TelaNotas
     */
    public TelaTarefas() {
        initComponents();
        setLocationRelativeTo(null);
        campoComentario.setText(comentarioSalvo);
        campoArquivo.setText(arquivoSalvo);
        getContentPane().setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        campoArquivo = new javax.swing.JTextField();
        lblEnviarArquivo = new javax.swing.JLabel();
        lblPesquisar = new javax.swing.JLabel();
        lblEnviarArquivo1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoComentario = new javax.swing.JTextArea();
        btLimpar = new GradientButton(new Color(1, 239, 110), new Color(0, 132, 246));
        btArquivar = new GradientButton(new Color(1, 239, 110), new Color(0, 132, 246));
        btEnviar = new GradientButton(new Color(245, 98, 98), new Color(30, 146, 247));
        btSair =  new GradientButton(new Color(207, 0, 0), new Color(255, 0, 0));
        jPanel1 = new GradientPanel(new Color(1, 239, 110), new Color(0, 132, 246));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));

        lblTitulo.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lblTitulo.setText("Mandar Tarefas");

        campoArquivo.setEditable(false);
        campoArquivo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campoArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoArquivoActionPerformed(evt);
            }
        });

        lblEnviarArquivo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblEnviarArquivo.setText("Enviar arquivo:");

        lblPesquisar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPesquisar.setForeground(new java.awt.Color(51, 51, 255));
        lblPesquisar.setText("Pesquisar no computador");
        lblPesquisar.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        lblPesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPesquisarMouseClicked(evt);
            }
        });

        lblEnviarArquivo1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblEnviarArquivo1.setText("Enviar comentário:");

        campoComentario.setColumns(20);
        campoComentario.setRows(5);
        jScrollPane1.setViewportView(campoComentario);

        btLimpar.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        btLimpar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btArquivar.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        btArquivar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btArquivar.setText("Arquivar");
        btArquivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btArquivarActionPerformed(evt);
            }
        });

        btEnviar.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        btEnviar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btEnviar.setText("Enviar");
        btEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEnviarActionPerformed(evt);
            }
        });

        btSair.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        btSair.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 88, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEnviarArquivo)
                            .addComponent(lblPesquisar))))
                .addContainerGap(429, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btEnviar)
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTitulo)
                            .addComponent(campoArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(btLimpar)
                        .addGap(37, 37, 37))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEnviarArquivo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btArquivar)
                        .addGap(29, 29, 29))))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btSair, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitulo))
                .addGap(7, 7, 7)
                .addComponent(lblEnviarArquivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btLimpar))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lblPesquisar)
                        .addGap(25, 25, 25)
                        .addComponent(lblEnviarArquivo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                        .addGap(31, 31, 31))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(btArquivar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btEnviar)
                        .addGap(67, 67, 67))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoArquivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoArquivoActionPerformed

    private void lblPesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPesquisarMouseClicked
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        int valorArquivo = fileChooser.showOpenDialog(this);
        
        if (valorArquivo == JFileChooser.APPROVE_OPTION) {
            java.io.File selecionado = fileChooser.getSelectedFile();
            campoArquivo.setText(selecionado.getAbsolutePath());
        }
    }//GEN-LAST:event_lblPesquisarMouseClicked

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        // TODO add your handling code here:
        campoArquivo.setText("");
        campoComentario.setText("");
    }//GEN-LAST:event_btLimparActionPerformed

    private void btArquivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btArquivarActionPerformed
        // TODO add your handling code here:
        comentarioSalvo = campoComentario.getText();
        arquivoSalvo = campoArquivo.getText();
        JOptionPane.showMessageDialog(null, "Tarefa arquivada. Não se esqueca de enviá-la.");
        try {
            TelaPrincipal principal = new TelaPrincipal();
            principal.setVisible(true);
            dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao ir para a tela principal: " + e.getMessage());
        }
    }//GEN-LAST:event_btArquivarActionPerformed

    private void btEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEnviarActionPerformed
        // TODO add your handling code here:
        String comentario = campoComentario.getText();
        String arquivo = campoArquivo.getText();
        
        if (arquivo.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Você deve enviar algum arquivo.");
        } else {
            JOptionPane.showMessageDialog(null, "Tarefa enviada!");
            campoArquivo.setText("");
            campoComentario.setText("");
            
            comentarioSalvo = "";
            arquivoSalvo = "";
        }
    }//GEN-LAST:event_btEnviarActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        // TODO add your handling code here:
        comentarioSalvo = campoComentario.getText();
        arquivoSalvo = campoArquivo.getText();
        
        try {
            TelaPrincipal principal = new TelaPrincipal();
            principal.setVisible(true);
            dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao ir para a tela principal: " + e.getMessage());
        }
    }//GEN-LAST:event_btSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaTarefas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaTarefas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaTarefas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaTarefas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaTarefas().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btArquivar;
    private javax.swing.JButton btEnviar;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btSair;
    private javax.swing.JTextField campoArquivo;
    private javax.swing.JTextArea campoComentario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEnviarArquivo;
    private javax.swing.JLabel lblEnviarArquivo1;
    private javax.swing.JLabel lblPesquisar;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
